# fly.toml for Discord bot

app = "gluconapoleiferin-divine-paper-9646"
primary_region = "sin"

[build]
  # optional: specify a builder if needed
  # builder = "heroku/buildpacks:20"

[deploy]
  release_command = ""  # leave empty for Discord bot

# Remove [http_service] entirely because Discord bots don't need HTTP
# Optionally, you can keep a tiny dummy HTTP server to prevent Fly from suspending
# Uncomment below if you want a dummy server
# [http_service]
#   internal_port = 8080
#   force_https = true
#   auto_stop_machines = "stop"
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
